---
title: "Senado"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, error = FALSE)
```
### Cámara de Senadores dividida POR BLOQUE

```{r, echo=FALSE}

library(tidyverse)
library(plyr)
library(ggparliament)
library(readxl)
library(ggthemes)
library(plotly)
library(readr)
library(dplyr)
library(ggplot2)
library(geofacet)
library(data.table)
library(highcharter)
library(scales)
library(paletteer)
library(shiny)
library(gganimate)
library(kableExtra)
senado_nomina <- read_excel("C:/Users/fefen/OneDrive/Documentos/RSTUDIO/data/DIPUTADOS/senado_nomina.xlsx")

#NOMBRES DE COLUMNAS
colnames(senado_nomina)[1] <- "Distrito"
colnames(senado_nomina)[2] <- "Nombre"
colnames(senado_nomina)[3] <- "Apellido"
colnames(senado_nomina)[4] <- "party_long"

#PARTIDOS
senado_nomina <- senado_nomina %>% mutate(
     seats = case_when(
       party_long == "Unidad Ciudadana"        ~ "1",
       party_long == "Frente Nacional y Popular"        ~ "1",
       party_long == "Frente Renovador de la Concordia Social"        ~ "1",
       party_long == "Juntos Somos Río Negro"        ~ "1",
       party_long == "Unidad Federal"        ~ "1",
        party_long == "Por Santa Cruz"~ "1",
       party_long == "Unión Cívica Radical"        ~ "1",
       party_long == "Partido por la Justicia Social"        ~ "1",
      party_long == "Frente PRO"        ~ "1",
      party_long == "Cambio Federal"        ~ "1",
      party_long == "La Libertad Avanza"        ~ "1",
      party_long == "Comunidad Neuquén"        ~ "1",
       ))

senado_nomina$seats <- as.double(senado_nomina$seats)

#COLORES
senado_nomina <- senado_nomina %>% mutate(
     colour = case_when(
       party_long == "Unidad Ciudadana"        ~ "#1c60ff",
       party_long == "Frente Nacional y Popular"        ~ "#4FA4FF",
       party_long == "Frente Renovador de la Concordia Social"        ~ "#A9D3FF",
       party_long == "Juntos Somos Río Negro"        ~ "#42ED3D",
       party_long == "Unidad Federal"        ~ "#2E1093",
        party_long == "Por Santa Cruz"~ "#150A3E",
       party_long == "Unión Cívica Radical"        ~ "#C70039",
       party_long == "Partido por la Justicia Social"        ~ "#A88C43",
      party_long == "Frente PRO"        ~ "#FFEC2D",
      party_long == "Cambio Federal"        ~ "#FF8221",
      party_long == "La Libertad Avanza"        ~ "#9143A8",
      party_long == "Comunidad Neuquén"        ~ "#FF60C7"
       ))

senado_nomina <- senado_nomina %>% mutate(
     orden = case_when(
      party_long == "Unidad Ciudadana"        ~ "1",
       party_long == "Frente Nacional y Popular"        ~ "2",
       party_long == "Frente Renovador de la Concordia Social"        ~ "3",
       party_long == "Juntos Somos Río Negro"        ~ "4",
        party_long == "Unidad Federal"        ~ "5",
       party_long == "Por Santa Cruz"        ~ "6",
       party_long == "Unión Cívica Radical"        ~ "7",
       party_long == "Partido por la Justicia Social"        ~ "8",
       party_long == "Frente PRO"        ~ "9",
       party_long == "Cambio Federal"        ~ "10",
       party_long == "La Libertad Avanza"        ~ "11",
      party_long == "Comunidad Neuquén"        ~ "12",
       ))

senado_nomina$orden <- as.double(senado_nomina$orden)

senado_nomina$party_long <- factor(as.character(senado_nomina$party_long), levels=c("Unidad Ciudadana","Frente Nacional y Popular","Frente Renovador de la Concordia Social","Juntos Somos Río Negro","Unidad Federal","Por Santa Cruz","Unión Cívica Radical","Partido por la Justicia Social","Frente PRO","Cambio Federal","La Libertad Avanza","Comunidad Neuquén"), labels = c("Unidad Ciudadana","Frente Nacional y Popular","Frente Renovador de la Concordia Social","Juntos Somos Río Negro","Unidad Federal","Por Santa Cruz","Unión Cívica Radical","Partido por la Justicia Social","Frente PRO","Cambio Federal","La Libertad Avanza","Comunidad Neuquén"))

senadores_por_bloque<- ggparliament::parliament_data(senado_nomina, #datos 
                                                       type = "semicircle", # forma del hemiciclo
                                                       parl_rows = 4, # cantidad de filas
                                                       party_seats = senado_nomina$seats, # número de bancas 
                                                       plot_order = senado_nomina$orden) %>% #orden de partidos en hemiciclo
  mutate(colour = as.character(colour)) %>% # vector de texto para codigo HEX de colores asignados previamente
  as_tibble()

grafico_senado_por_bloque <- senadores_por_bloque %>% as_tibble() %>% 
  ggplot(aes(x, y, color = party_long, text = paste0("Nombre: ", Nombre, "<br> Apellido: ", Apellido, "\n", "Distrito: ", Distrito, "\n", "Bloque: ", party_long, "\n", "Voto: ", voto_al_dnu))) +
  geom_parliament_seats(size = 4) + # tamaño de bancas (puntos)
  draw_majoritythreshold(n = 36, label = F, type = "semicircle", linesize = 0.5) + # dibuja el limite de mayoría 
  scale_colour_manual(values = senado_nomina$colour, #asigno colores 
                      limits = senado_nomina$party_long)  +
  labs(title = "Honorable Senado de la Nación y su postura frente al DNU 70/23",
       subtitle = "por bloque",
       x = "",
       y = "",
       caption = "Fuente: Cámara de Senadores de la Nación",
       colour = NULL) +
  theme_minimal() +
  theme(panel.grid = element_blank(), 
        axis.text = element_blank(),
        legend.text = element_text(size = 10),
        legend.position = c('bottom')
        )

grafico_senado_por_bloque

grafico_senado_por_bloque_plotly <- ggplotly(grafico_senado_por_bloque, tooltip = "text")%>%
  layout(title = list(text = paste0('Honorable Senado de la Nación y su postura frente al DNU 70/23',
                                    '<br>',
                                    '<sup>',
                                    'por bloque',
                                    '</sup>')),
         legend = list(orientation = "h", x = 0, y = -0.05), 
                                           annotations = list(x = 1, 
                                                              y = -0.04,
                                                              text = "Fuente: Cámara de Senadores de la Nación",
                                                              showarrow = F,
                                                              xref='paper', yref='paper',
                                                              xanchor='right', yanchor='auto',
                                                              xshift=0, yshift=0,
                                                              font=list(size=12, color="black")))

grafico_senado_por_bloque_plotly

```


### Cámara de Senadores dividida POR VOTO


```{r, echo=FALSE}

knitr::opts_chunk$set(echo = FALSE)

library(ggparliament)
senado_nomina <- read_excel("C:/Users/fefen/OneDrive/Documentos/RSTUDIO/data/DIPUTADOS/senado_nomina.xlsx")

#NOMBRES DE COLUMNAS
colnames(senado_nomina)[1] <- "Distrito"
colnames(senado_nomina)[2] <- "Nombre"
colnames(senado_nomina)[3] <- "Apellido"
colnames(senado_nomina)[4] <- "party_long"

senado_nomina <- senado_nomina %>% mutate(
     seats = case_when(
       voto_al_dnu == "En contra"        ~ "1",
       voto_al_dnu == "Posible en contra"        ~ "1",
       voto_al_dnu == "Abstención"        ~ "1",
       voto_al_dnu == "Indefinido"        ~ "1",
      voto_al_dnu == "Posible a favor"        ~ "1",
       voto_al_dnu == "A favor"        ~ "1",
       ))

senado_nomina$seats <- as.double(senado_nomina$seats)

senado_nomina <- senado_nomina %>% mutate(
     colour = case_when(
       voto_al_dnu == "En contra"        ~ "#F95D50",
       voto_al_dnu == "Posible en contra"        ~ "#F5978F",
       voto_al_dnu == "Abstención"        ~ "#B5C4FF",
       voto_al_dnu == "Indefinido"        ~ "#A1A1A1",
      voto_al_dnu == "Posible a favor"        ~ "#C4FFB5",
       voto_al_dnu == "A favor"        ~ "#90DB7D",
       ))

senado_nomina <- senado_nomina %>% mutate(
     orden = case_when(
      voto_al_dnu== "En contra"        ~ "1",
       voto_al_dnu == "Posible en contra"        ~ "2",
       voto_al_dnu == "Abstención"        ~ "3",
       voto_al_dnu == "Indefinido"        ~ "4",
      voto_al_dnu == "Posible a favor"        ~ "5",
       voto_al_dnu == "A favor"        ~ "6",
       ))

senado_nomina$orden <- as.double(senado_nomina$orden)

senado_nomina$voto_al_dnu <- factor(as.character(senado_nomina$voto_al_dnu), levels=c("En contra", "Posible en contra", "Abstención", "Indefinido", "Posible a favor", "A favor"), labels = c("En contra", "Posible en contra", "Abstención", "Indefinido", "Posible a favor", "A favor"))

senadores_por_voto<- ggparliament::parliament_data(senado_nomina, #datos 
                                                       type = "semicircle", # forma del hemiciclo
                                                       parl_rows = 4, # cantidad de filas
                                                       party_seats = senado_nomina$seats, # número de bancas 
                                                       plot_order = senado_nomina$orden) %>% #orden de partidos en hemiciclo
  mutate(colour = as.character(colour)) %>% # vector de texto para codigo HEX de colores asignados previamente
  as_tibble()

senadores_a_favor <- senado_nomina %>%
  filter(voto_al_dnu %in% c("A favor", "Posible a favor", "Abstención", "Indefinido"))

grafico_senado_por_voto <- senadores_por_voto %>% as_tibble() %>% 
  ggplot(aes(x, y, color = voto_al_dnu, text = paste0("Nombre: ", Nombre, "<br>Apellido: ", Apellido, "\n", "Distrito: ", Distrito, "\n", "Bloque: ", party_long , "\n", "Voto: ", voto_al_dnu))) +
  geom_parliament_seats(size = 4) +
  draw_majoritythreshold(n = 128, label = F, type = "semicircle", linesize = 0.5) +
  scale_y_continuous(labels = scales::percent) +
  scale_colour_manual(values = senado_nomina$colour, # Utiliza la columna de colores
                      limits = senado_nomina$voto_al_dnu) +
  labs(title = "Honorable Senado de la Nación y su postura frente al DNU 70/23",
       subtitle = "por voto",
       x = "",
       y = "",
       caption = "Fuente: Cámara de Senadores de la Nación",
       colour = NULL) +
  theme_minimal() +
  theme(panel.grid = element_blank(), 
        axis.text = element_blank(),
        legend.text = element_text(size = 10),
        legend.position = c('bottom'))

grafico_senado_por_voto

grafico_senado_por_voto_plotly <- ggplotly(grafico_senado_por_voto, tooltip = "text")%>%
  layout(title = list(text = paste0('Honorable Senado de la Nación y su postura frente al DNU 70/23',
                                    '<br>',
                                    '<sup>',
                                    'por voto',
                                    '</sup>')),
         legend = list(orientation = "h", x = 0, y = -0.05), 
                                           annotations = list(x = 1, 
                                                              y = -0.04,
                                                              text = "Fuente: Cámara de Senadores de la Nación",
                                                              showarrow = F,
                                                              xref='paper', yref='paper',
                                                              xanchor='right', yanchor='auto',
                                                              xshift=0, yshift=0,
                                                              font=list(size=12, color="black")))
grafico_senado_por_voto_plotly
``` 

### Cantidad de votos por tipo de voto
``` {r}
# Crear un resumen de la cantidad de votos por categoría
resumen_votos <- senado_nomina %>%
  group_by(voto_al_dnu) %>%
  summarise(cantidad = n(), colour = unique(colour))

# Crear el gráfico interactivo de barras
grafico_resumen_votos_plotly <- plot_ly(resumen_votos, x = ~factor(voto_al_dnu, levels=c("A favor", "Posible a favor", "Abstención", "Indefinido", "Posible en contra", "En contra")), y = ~cantidad, type = 'bar', marker = list(color = resumen_votos$colour)) %>%
  layout(title = "Resumen de Votos del Senado sobre el DNU 70/23",
         xaxis = list(title = "Voto"),
         yaxis = list(title = "Cantidad"),
         showlegend = FALSE)

# Mostrar el gráfico interactivo de barras
grafico_resumen_votos_plotly
```

``` {r}


library(viridis)

# Crear un vector de colores que se correspondan con las categorías de voto_al_dnu
colores <- c("#F95D50", "#F5978F", "#B5C4FF","#C4FFB5", "#90DB7D")

# Agrupar y contar los votos por bloque y tipo de voto
votos_por_bloque <- senado_nomina %>%
  filter(party_long %in% c("Unidad Ciudadana", "Frente Nacional y Popular", "Frente Renovador de la Concordia Social", "Juntos Somos Río Negro", "Unidad Federal", "Por Santa Cruz", "Unión Cívica Radical", "Partido por la Justicia Social", "Frente PRO", "Cambio Federal", "La Libertad Avanza", "Comunidad Neuquén")) %>%
  group_by(party_long, voto_al_dnu) %>%
  summarise(count = n())

# Crear el gráfico de barras apiladas con ggplot
plot_votos_por_bloque <- ggplot(votos_por_bloque, aes(x = party_long, y = count, fill = voto_al_dnu, text = paste("Bloque:", party_long, "<br>", "Tipo de voto:", voto_al_dnu, "<br>", "Cantidad:", count))) +
  geom_bar(stat = "identity") +
  scale_fill_manual(values = colores) +  # Utilizar la paleta de colores definida
  theme_minimal() +
  labs(x = "Bloque",
       y = "Cantidad de votos",
       fill = "Tipo de voto",
       title = "Cantidad de votos por bloque",
       caption = "Fuente: Honorable Senado de la Nación") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

# Convertir el gráfico de ggplot a plotly
plotly_plot <- ggplotly(plot_votos_por_bloque, tooltip = "text")

# Mostrar el gráfico interactivo
plotly_plot

```

### Tabla con información pública de los senadores que están a favor o indecisos del DNU 70/23

``` {r}

# Display the entire dataframe as an HTML table with styling
knitr::kable(
  senadores_a_favor %>% select(-voto_ley_omnibus, -seats, -colour, -orden),
  format = "html",
  caption = "Senadores a favor o indecisos"
) %>%
  kable_styling(
    full_width = FALSE, # Allow the table to have a fixed width
    bootstrap_options = c("striped", "hover", "condensed"), # Bootstrap table options
    position = "center", # Center the table
    latex_options = c("scale_down") # Scale down for LaTeX output
  )
```


por Frankiturr0